# Generated by Django 4.2.19 on 2025-03-05 02:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Emri")),
                (
                    "issuing_organization",
                    models.CharField(
                        max_length=200, verbose_name="Organizata lëshuese"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Data e lëshimit")),
                ("expiry_date", models.DateField(verbose_name="Data e skadimit")),
                (
                    "document",
                    models.FileField(
                        upload_to="certifications/", verbose_name="Dokumenti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certifikim",
                "verbose_name_plural": "Certifikimet",
            },
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Emri")),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Emri shkencor",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Përshkrimi"),
                ),
                (
                    "growing_season",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Sezoni i rritjes"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="crops/", verbose_name="Imazhi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kulturë Bujqësore",
                "verbose_name_plural": "Kulturat Bujqësore",
            },
        ),
        migrations.CreateModel(
            name="CultivationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Emri")),
                ("description", models.TextField(verbose_name="Përshkrimi")),
            ],
            options={
                "verbose_name": "Metoda e Kultivimit",
                "verbose_name_plural": "Metodat e Kultivimit",
            },
        ),
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farm_name",
                    models.CharField(max_length=200, verbose_name="Emri i fermës"),
                ),
                (
                    "farm_description",
                    models.TextField(blank=True, verbose_name="Përshkrimi i fermës"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="farmer_profiles/",
                        verbose_name="Imazhi i profilit",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numri i telefonit"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="Faqja e internetit"),
                ),
                (
                    "year_established",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Viti i themelimit",
                    ),
                ),
                (
                    "total_land_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Sipërfaqja totale e tokës (ha)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="I verifikuar"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data e regjistrimit"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="Përditësuar më"),
                ),
                (
                    "certifications",
                    models.ManyToManyField(
                        blank=True, related_name="farmers", to="farmer.certification"
                    ),
                ),
                (
                    "cultivation_methods",
                    models.ManyToManyField(
                        related_name="farmers", to="farmer.cultivationmethod"
                    ),
                ),
            ],
            options={
                "verbose_name": "Profili i Fermerit",
                "verbose_name_plural": "Profilet e Fermerëve",
            },
        ),
        migrations.CreateModel(
            name="FarmLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Adresa")),
                ("city", models.CharField(max_length=100, verbose_name="Qyteti")),
                ("region", models.CharField(max_length=100, verbose_name="Rajoni")),
                (
                    "country",
                    models.CharField(
                        default="Shqipëri", max_length=100, verbose_name="Shteti"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Gjerësia gjeografike",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Gjatësia gjeografike",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendndodhja e Fermës",
                "verbose_name_plural": "Vendndodhjet e Fermave",
            },
        ),
        migrations.CreateModel(
            name="ProductionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("planting", "Mbjellje"),
                            ("fertilizing", "Plehërim"),
                            ("irrigating", "Ujitje"),
                            ("pest_control", "Kontroll i dëmtuesve"),
                            ("harvesting", "Vjelje"),
                            ("other", "Tjetër"),
                        ],
                        max_length=20,
                        verbose_name="Lloji i aktivitetit",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("description", models.TextField(verbose_name="Përshkrimi")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="production_logs/",
                        verbose_name="Foto",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Shënime")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Krijuar më"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Përditësuar më"),
                ),
                (
                    "blockchain_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hash Blockchain",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_logs",
                        to="farmer.crop",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_logs",
                        to="farmer.farmerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regjistri i Prodhimit",
                "verbose_name_plural": "Regjistrat e Prodhimit",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farmers",
                to="farmer.farmlocation",
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FarmerCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Sipërfaqja e tokës (ha)",
                    ),
                ),
                (
                    "estimated_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Rendimenti i përllogaritur (kg/ha)",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmer.crop"
                    ),
                ),
                (
                    "cultivation_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farmer.cultivationmethod",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmer.farmerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kultura e Fermerit",
                "verbose_name_plural": "Kulturat e Fermerit",
                "unique_together": {("farmer", "crop")},
            },
        ),
    ]
