# Generated by Django 4.2.9 on 2025-03-05 22:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import logistics.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("driver_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "license_number",
                    models.CharField(max_length=50, verbose_name="License Number"),
                ),
                (
                    "license_expiry",
                    models.DateField(verbose_name="License Expiry Date"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "emergency_contact",
                    models.CharField(max_length=100, verbose_name="Emergency Contact"),
                ),
                (
                    "emergency_phone",
                    models.CharField(max_length=20, verbose_name="Emergency Phone"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Is Available"),
                ),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("shipment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tracking_number",
                    models.CharField(
                        default=logistics.models.generate_tracking_number,
                        max_length=50,
                        unique=True,
                        verbose_name="Tracking Number",
                    ),
                ),
                ("origin", models.CharField(max_length=100, verbose_name="Origin")),
                (
                    "destination",
                    models.CharField(max_length=100, verbose_name="Destination"),
                ),
                (
                    "sender_name",
                    models.CharField(max_length=100, verbose_name="Sender Name"),
                ),
                (
                    "sender_phone",
                    models.CharField(max_length=20, verbose_name="Sender Phone"),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=100, verbose_name="Receiver Name"),
                ),
                (
                    "receiver_phone",
                    models.CharField(max_length=20, verbose_name="Receiver Phone"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("picking_up", "Picking Up"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("at_warehouse", "At Warehouse"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("delayed", "Delayed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "departure_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Departure Date"
                    ),
                ),
                (
                    "estimated_arrival",
                    models.DateTimeField(
                        default=logistics.models.default_estimated_arrival,
                        verbose_name="Estimated Arrival",
                    ),
                ),
                (
                    "actual_arrival",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual Arrival"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "volume",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Volume (m³)",
                    ),
                ),
                (
                    "package_count",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Package Count",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "insurance_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Insurance Value",
                    ),
                ),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Special Instructions"
                    ),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Current Location",
                    ),
                ),
                (
                    "is_hazardous",
                    models.BooleanField(default=False, verbose_name="Is Hazardous"),
                ),
                (
                    "requires_refrigeration",
                    models.BooleanField(
                        default=False, verbose_name="Requires Refrigeration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportCompany",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="Contact Person"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Contact Phone"),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "registration_number",
                    models.CharField(max_length=50, verbose_name="Registration Number"),
                ),
                (
                    "tax_number",
                    models.CharField(max_length=50, verbose_name="Tax Number"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Transport Company",
                "verbose_name_plural": "Transport Companies",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("warehouse_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "capacity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Capacity (m³)",
                    ),
                ),
                (
                    "current_utilization",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Current Utilization (m³)",
                    ),
                ),
                ("manager", models.CharField(max_length=100, verbose_name="Manager")),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Contact Phone"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "temperature_controlled",
                    models.BooleanField(
                        default=False, verbose_name="Temperature Controlled"
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("maximum", "Maximum"),
                        ],
                        default="medium",
                        max_length=50,
                        verbose_name="Security Level",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="logistics.transportcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("vehicle_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("truck", "Truck"),
                            ("van", "Van"),
                            ("refrigerated", "Refrigerated Truck"),
                            ("pickup", "Pickup Truck"),
                        ],
                        max_length=50,
                        verbose_name="Vehicle Type",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Plate Number"
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "capacity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Capacity (kg)",
                    ),
                ),
                (
                    "availability",
                    models.BooleanField(default=True, verbose_name="Is Available"),
                ),
                (
                    "last_maintenance",
                    models.DateField(verbose_name="Last Maintenance Date"),
                ),
                (
                    "next_maintenance",
                    models.DateField(verbose_name="Next Maintenance Date"),
                ),
                (
                    "insurance_expiry",
                    models.DateField(verbose_name="Insurance Expiry Date"),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Current Location",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="logistics.transportcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("picking_up", "Picking Up"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("at_warehouse", "At Warehouse"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("delayed", "Delayed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="Details"),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recorded By",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="logistics.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Event",
                "verbose_name_plural": "Tracking Events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="logistics.transportcompany",
                verbose_name="Transport Company",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbound_shipments",
                to="logistics.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="logistics.driver",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outbound_shipments",
                to="logistics.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="logistics.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drivers",
                to="logistics.transportcompany",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
