# Generated by Django 4.2.19 on 2025-03-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipment",
            options={"verbose_name": "Shipment", "verbose_name_plural": "Shipments"},
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="is_hazardous",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="requires_refrigeration",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="driver",
            name="emergency_contact_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Emergency Contact"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="emergency_contact_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Emergency Contact"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Destination"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Destination"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Origin"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Origin"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Receiver Name"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_name_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Receiver Name"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="sender_name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Sender Name"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="sender_name_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Sender Name"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="special_instructions_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Special Instructions"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="special_instructions_sq",
            field=models.TextField(
                blank=True, null=True, verbose_name="Special Instructions"
            ),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="details_en",
            field=models.TextField(blank=True, null=True, verbose_name="Details"),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="details_sq",
            field=models.TextField(blank=True, null=True, verbose_name="Details"),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="location_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="location_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="transportcompany",
            name="address_en",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="transportcompany",
            name="address_sq",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="transportcompany",
            name="contact_person_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contact Person"
            ),
        ),
        migrations.AddField(
            model_name="transportcompany",
            name="contact_person_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contact Person"
            ),
        ),
        migrations.AddField(
            model_name="transportcompany",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="transportcompany",
            name="name_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_location_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Current Location"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_location_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Current Location"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Model"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Model"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="address_en",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="address_sq",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="location_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="location_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="manager_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Manager"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="manager_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Manager"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="name_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
    ]
