# Generated by Django 4.2.19 on 2025-03-05 02:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Emri")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Përshkrimi"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Imazhi",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="product.category",
                        verbose_name="Kategoria prind",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoritë",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Emri")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Përshkrimi")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Çmimi",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Çmimi me ulje",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("piece", "Copë"),
                            ("box", "Kuti"),
                            ("bunch", "Tufë"),
                        ],
                        default="kg",
                        max_length=10,
                        verbose_name="Njësia",
                    ),
                ),
                (
                    "minimum_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Sasia minimale e porosisë",
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Sasia në gjendje",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("in_stock", "Në gjendje"),
                            ("out_of_stock", "Nuk ka në gjendje"),
                            ("coming_soon", "Së shpejti"),
                            ("pre_order", "Para-porosi"),
                        ],
                        default="in_stock",
                        max_length=20,
                        verbose_name="Disponueshmëria",
                    ),
                ),
                (
                    "is_organic",
                    models.BooleanField(default=False, verbose_name="Organik"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="I veçantë"),
                ),
                (
                    "harvest_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data e vjeljes"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data e skadencës"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Krijuar më"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Përditësuar më"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="product.category",
                        verbose_name="Kategoria",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="farmer.crop",
                        verbose_name="Kultura",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="farmer.farmerprofile",
                        verbose_name="Fermeri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produktet",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Pyetja")),
                (
                    "answer",
                    models.TextField(blank=True, null=True, verbose_name="Përgjigja"),
                ),
                (
                    "asked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Pyetur më"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Përgjigjur më"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Tregon nëse pyetja është e dukshme për të gjithë",
                        verbose_name="Publike",
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Përgjigjur nga",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="product.product",
                        verbose_name="Produkti",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pyetësi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pyetje për Produktin",
                "verbose_name_plural": "Pyetjet për Produktet",
                "ordering": ["-asked_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="Imazhi"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Imazh kryesor"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Teksti alternativ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Krijuar më"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                        verbose_name="Produkti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imazh i Produktit",
                "verbose_name_plural": "Imazhet e Produkteve",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Vlerësimi",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Komenti")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Krijuar më"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Përditësuar më"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Tregon nëse vlerësimi është nga një blerës i verifikuar",
                        verbose_name="I verifikuar",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="product.product",
                        verbose_name="Produkti",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Përdoruesi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vlerësim",
                "verbose_name_plural": "Vlerësimet",
                "ordering": ["-created_at"],
                "unique_together": {("product", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="product_pro_name_b60cd1_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="product_pro_slug_33a021_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="product_pro_created_57e07a_idx"
            ),
        ),
    ]
