# Generated by Django 4.2.19 on 2025-03-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_sq",
            field=models.TextField(blank=True, null=True, verbose_name="Përshkrimi"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_sq",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Emri"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_sq",
            field=models.TextField(blank=True, null=True, verbose_name="Përshkrimi"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_sq",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Emri"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Alternative Text"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text_sq",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Teksti alternativ"
            ),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="answer_en",
            field=models.TextField(blank=True, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="answer_sq",
            field=models.TextField(blank=True, null=True, verbose_name="Përgjigja"),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="question_en",
            field=models.TextField(blank=True, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="question_sq",
            field=models.TextField(blank=True, null=True, verbose_name="Pyetja"),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_en",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_sq",
            field=models.TextField(blank=True, null=True, verbose_name="Komenti"),
        ),
    ]
