# Generated by Django 4.2.19 on 2025-03-09 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0002_category_description_en_category_description_sq_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farmer", "0002_certification_issuing_organization_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Krijuar më"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Përditësuar më"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Përdoruesi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shportë",
                "verbose_name_plural": "Shportat",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numri i porosisë"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Në pritje"),
                            ("confirmed", "Konfirmuar"),
                            ("processing", "Në përpunim"),
                            ("shipping", "Në transport"),
                            ("delivered", "Dorëzuar"),
                            ("cancelled", "Anuluar"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statusi",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Shuma totale"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Para në dorë"),
                            ("bank_transfer", "Transfertë bankare"),
                            ("card", "Kartë krediti/debiti"),
                        ],
                        max_length=20,
                        verbose_name="Metoda e pagesës",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(verbose_name="Adresa e dorëzimit"),
                ),
                (
                    "shipping_address_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Shipping Address"
                    ),
                ),
                (
                    "shipping_address_sq",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresa e dorëzimit"
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(max_length=100, verbose_name="Qyteti"),
                ),
                (
                    "shipping_city_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "shipping_city_sq",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Qyteti"
                    ),
                ),
                (
                    "shipping_phone",
                    models.CharField(max_length=20, verbose_name="Telefoni"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Shënime")),
                (
                    "notes_en",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "notes_sq",
                    models.TextField(blank=True, null=True, verbose_name="Shënime"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Krijuar më"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Përditësuar më"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blerësi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Porosi",
                "verbose_name_plural": "Porositë",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Shuma"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Në pritje"),
                            ("completed", "Kompletuar"),
                            ("failed", "Dështuar"),
                            ("refunded", "Rimbursuar"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statusi",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="ID e transaksionit",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Para në dorë"),
                            ("bank_transfer", "Transfertë bankare"),
                            ("card", "Kartë krediti/debiti"),
                        ],
                        max_length=20,
                        verbose_name="Metoda e pagesës",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Krijuar më"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Përditësuar më"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Shënime")),
                (
                    "notes_en",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "notes_sq",
                    models.TextField(blank=True, null=True, verbose_name="Shënime"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="marketplace.order",
                        verbose_name="Porosia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaksion",
                "verbose_name_plural": "Transaksionet",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Emri i produktit"),
                ),
                (
                    "product_name_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "product_name_sq",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Emri i produktit",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sasia"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Çmimi për njësi"
                    ),
                ),
                ("unit", models.CharField(max_length=10, verbose_name="Njësia")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Nëntotali"
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farmer.farmerprofile",
                        verbose_name="Fermeri",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="marketplace.order",
                        verbose_name="Porosia",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.product",
                        verbose_name="Produkti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt i porosisë",
                "verbose_name_plural": "Produktet e porosisë",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sasia"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Çmimi për njësi"
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Shtuar më"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="marketplace.cart",
                        verbose_name="Shporta",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Produkti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt në shportë",
                "verbose_name_plural": "Produktet në shportë",
                "unique_together": {("cart", "product")},
            },
        ),
    ]
